# Generated by Django 5.0.2 on 2024-03-07 07:49

import apps.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='favicon_ico',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils.upload_favicon, validators=[django.core.validators.FileExtensionValidator(['ico'])], verbose_name='favicon (.ico)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='favicon_png',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.upload_favicon, validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='favicon (.png)'),
        ),
    ]
